name: app_delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  intl: ^0.19.0
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/categories/